@startuml

actor "User" as u

cloud "AWS VPC" {
    node "EC2 instance" {
      rectangle "Node server" {
        artifact "Frontend" as f
      }
        stack "docker-compose" {
            rectangle "Docker container" as d2 {
                rectangle "JVM" {
                    artifact "Backend" as b
                }
            }
        }
        f -down-> b
    }
}

u -right-> f

@enduml
